# Habilitar CORS
quarkus.http.cors.enabled=true

# Em desenvolvimento, permitir qualquer origem (inclusive http://localhost:5173)
%dev.quarkus.http.cors.origins=/.*/

# Métodos que o frontend pode usar
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Cabeçalhos permitidos
%dev.quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Permitir credenciais (cookies de sessão)
%dev.quarkus.http.cors.access-control-allow-credentials=true